"""empty message

Revision ID: dc5e39351244
Revises: d7ea4fa1a421
Create Date: 2026-02-22 09:48:49.954228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc5e39351244'
down_revision = 'd7ea4fa1a421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=False))
        batch_op.drop_column('roel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
